feat: add property to widget DOM elements
NearSocial/VM pull request #131
Opened 2023-09-28 21:13 UTC by roshaans

2023-10-02 18:01 UTC, evgenykuzyakov commented
I would still prefer to make it optional and not enabled by default. We should add feature flags to the VM, to enable certain optional actions.

2023-10-03 16:59 UTC, roshaans commented
> I would still prefer to make it optional and not enabled by default. We should add feature flags to the VM, to enable certain optional actions.

Would you prefer a simple `featureFlagsMap` to be passed to the VM or create a `FeatureFlags` class to be created?

This class will make sure we keep track of all new feature flags in one place and that there is a unified way to check if a feature is enabled or not.

This is what the interface would roughly look like, but it'd be in Javascript

```javascript
interface IFeatureFlags {
  isFeatureEnabled(featureName: string): boolean;
  enableFeature(featureName: string): void;
  disableFeature(featureName: string): void;
  setMultipleFeatures(featuresMap: Map<string, boolean>): void;
  getAllFeatures(): { featureName: string, isEnabled: boolean }[];
}

class FeatureFlags implements IFeatureFlags {
  private features: Map<string, boolean>;

  constructor() {
    this.features = new Map([
      ['addWidgetSrcAttribute', false]
// other features as we add them
    ]);
  }

  // ... (rest of the methods)
}
```

2023-10-03 17:11 UTC, evgenykuzyakov commented
A simple map should be fine. E.g. an object `features`, with attributes like `enableWidgetSrcDataKey: true`

2023-10-06 16:57 UTC, evgenykuzyakov requested changes
Please rebase to `dev` and add changes to CHANGELOG.md

2023-10-06 16:57 UTC, evgenykuzyakov commented on src/lib/vm/vm.js
> +    if (this.vm.near.features.enableWidgetSrcDataKey == true) {
Probably safer.

```suggestion
    if (this.vm.near?.features?.enableWidgetSrcDataKey == true) {
```

2023-10-06 16:57 UTC, evgenykuzyakov commented on src/lib/data/near.js
> +  features = {},
Let's add a comment above the `_initNear` that defines which features are available to keep track in one place. With description of a feature.

2023-10-09 20:54 UTC, evgenykuzyakov approved these changes

2023-10-10 16:43 UTC, evgenykuzyakov commented on src/lib/vm/vm.js
> +      attributes["data-key"] = attributes["data-key"] ?? this.vm.widgetSrc;
```suggestion
      attributes["data-widgetSrc"] = attributes["data-widgetSrc"] ?? this.vm.widgetSrc;
```

2023-10-10 16:44 UTC, evgenykuzyakov commented on src/lib/data/near.js
> + * - enableWidgetSrcDataKey: Allows enabling the widget source data-key for rendered DOM elements. Disabled by default.
```suggestion
 * - enableWidgetSrcDataKey: Allows enabling the widget source data-widgetSrc for rendered DOM elements. Disabled by default.
```

2023-10-10 16:45 UTC, evgenykuzyakov requested changes
Please add changes to `CHANGELOG.md`

2023-10-10 18:41 UTC, evgenykuzyakov approved these changes

2023-10-10 20:00 UTC, merged

2023-11-02 09:15 UTC, alsakhaev commented
Do we really need to add a `data-component' attribute to every DOM node? Isn't just the root node enough?
Check out my commit [here] (https://github.com/dapplets/near-social-vm/commit/f9008dd6ddac2402f6bc3095dcfe0a00c14dbcf1)

Also I ran into the React warning: 
```
Warning: Invalid prop `data-component` passed to `React.Fragment`. React.Fragment can only have key and child props.
```
We should check that a node is not a React.Fragment before adding the attribute. I did it with the `isReactObject(result)` function.