feature: adds redirect map support for VM.require
NearSocial/VM pull request #134
Opened 2023-10-07 06:24 UTC by elliotBraem

Allows local module development when using VM.require.

Moves computeSrcOrCode to a utility class so it can be shared with VM.require, then checks if code exists in redirect map before doing Social.get

2023-10-07 18:37 UTC, evgenykuzyakov requested changes
Rebase to `dev` branch. Don't need to bump `package.json` for features

2023-10-07 18:37 UTC, evgenykuzyakov commented on src/lib/vm/vm.js
>      const vm = this.getVmInstance(code, src);
This should be updated based on `srcOrCode?.src`
```suggestion
    const vm = this.getVmInstance(code, srcOrCode?.src);
```

2023-10-07 18:37 UTC, evgenykuzyakov commented on src/lib/vm/vm.js
> +    console.log(code);
please remove
```suggestion
```

2023-10-07 19:24 UTC, evgenykuzyakov commented on CHANGELOG.md
> +- Add support for VM.require when using redirectMap.
There is example below. Just move to the top of the list

2023-10-07 19:33 UTC, elliotBraem commented
Made the requested changes, rebased to dev branch, but have now noticed something:

I get the error:

<img width="742" alt="Screenshot 2023-10-07 at 3 11 25 PM" src="https://github.com/NearSocial/VM/assets/16282460/ee671680-dfdd-49a3-adc6-6bd9b6983398">

This isn't broken by my change, the same is visible when using a component w/ VM.require on the dev near social gateway:
https://dev.near.social/discover.near/widget/ProjectFeed


**Found the solution**

Need to bind this to VM during initGlobalFunctions

```javascript
      VM: {
        require: this.vmRequire.bind(this),
      },
```

Have added this to PR. It's all working as expected 👍

2023-10-07 19:59 UTC, evgenykuzyakov requested changes
I think we need to handle `getVmInstance` differently if the `src` not available. E.g. if the code is passed directly, then the src will be `null` or `undefined`. In this case we should store by the `code` instead.

Maybe we should store all VM instances in `this.vmInstances` by the code.

2023-10-09 16:44 UTC, evgenykuzyakov approved these changes

2023-10-09 16:45 UTC, merged